config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :posts, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
  	 get :search, on: :collection
  	 resource :favorites, only: [:create, :destroy]
     resources :post_comments, onyl: [:create, :destroy]
  end



  resources :users, only: [:new, :create, :show, :edit, :update]

  root 'users#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
      root_path
   	end
   	def after_sign_out_path_for(resource)
      root_path
    end
	protected
	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.new(post_id: post.id)
		favorite.save
		redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.find_by(post_id: post.id)
		favorite.destroy
		redirect_to post_path(post)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		post =Post.find(params[:post_id])
		comment = PostComment.new(post_comment_params)
		comment.post_id = post.id
		comment.user_id = current_user.id
		comment.save
		redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:poat_id])
		favorite = current_user.favorites.find_by(post_id: post.id)
		favorite.destroy
		redirect_to post_path(post)
	end

	private
	def post_comment_params
	    params.require(:post_comment).permit(:comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def index
		@posts = Post.all.order(created_at: :desc)
		@users = User.all.order(created_at: :desc)
	end

	def show
		@post = Post.find(params[:id])
		@post.user#postのデータに紐づくuserのデータを取ってくる
		@post_comment = PostComment.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])
		post.update(post_params)
		redirect_to user_path(current_user.id)
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.save
		redirect_to posts_path(@post.id)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to user_path(current_user.id)
	end

	def search
	    if params[:recipe_name].present?
	      @posts = Post.where('recipe_name LIKE ?', "%#{params[:recipe_name]}%")
	    else
	      @posts = Post.none
	    end
    end

	private
	def post_params
		params.require(:post).permit(:recipe_name, :image, :caption)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def top
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path(@user.id)
	end


	private
	def user_params
		params.require(:user).permit(:profile_image, :name, :userinfo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Recipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-inverse">
    <div class="container">

    <span class="text-muted">Recipe Diary</span>

    <div id="slidemenu">
      <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
      <% if user_signed_in? %>

      <li class="">
        <%= link_to "Home", posts_path, class:"glyphicon glyphicon-home home" %>
      </li>

      <li class="">
        <%= link_to 'My recipe', user_path(current_user), class:"glyphicon glyphicon-user" %>
      </li>

      <li class="">
          <%= link_to "Post", new_post_path, class:"glyphicon glyphicon-cutlery" %>
      </li>

      <li class="">
          <%= link_to "Search", search_posts_path, class:"glyphicon glyphicon-search" %>
      </li>

      <li class="">
        <%= link_to "Logout", destroy_user_session_path,method: :delete, class:"glyphicon glyphicon-share" %>
      </li>


    <% else %>
      <li class="">
        <%= link_to "Home", root_path %>
      </li>
      <li class="">
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "Login", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>
</div>
</header>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="wrap">
			<div class="space"></div>
			 <div class="changespace">
			  <div class="profile_gazou">
				<%= attachment_image_tag @post.user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img" %>
			  </div>
			<div class="profile_name">
				<div class="name_space">
				 <%= @post.user.name %>
			    </div>

			<div class="recipe_title">
				  <p class="underline"><%= @post.recipe_name %></p>
		    </div>
		    </div>

			<div class="content_gazou">
				<div class="gazou">
				<%= attachment_image_tag @post, :image, format: 'jpeg', size: "600x400" %>
				</div>
			</div>

			<div class="change-area">
				<%= form_for(@post) do |f| %>
			       <%=f.text_area :caption, size: "50x2" %>
			       <%= f.submit "変更" %>
			    <% end %>
			</div>
		    </div>
	   </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="wrap">
			<% @posts.each do |post| %>
			<div class="space"></div>
			<div class="sidespace">
			<div class="profile_gazou">
				<%= attachment_image_tag post.user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img" %>
			</div>
			<div class="profile_name">
				<div class="name_space">
				 <%= post.user.name %>
				</div>
				 <div class="recipe_title">
				  <p class="underline"><%= post.recipe_name %></p>
			    </div>
			</div>
			<div class="content_gazou">
				<div class="gazou">
				<%= link_to post_path(post) do %>
				 <%= attachment_image_tag post, :image, format: 'jpeg', size: "600x400" %>
				<% end %>
				</div>
			</div>
			<div class="content_comment">
			    <div class="recipe_caption">
				  <%= post.caption %>
			    </div>
				<% if post.favorited_by?(current_user) %>
					<%= link_to post_favorites_path(post), method: :delete do %>
				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				    <p class="glyphicon glyphicon-thumbs-up"></p>
					<%= post.favorites.count %>
				    <% end %>
				<% else %>
				    <%= link_to post_favorites_path(post), method: :post do %>
					<i class="fa fa-heart-o" aria-hidden="true"></i>
					<p class="glyphicon glyphicon-thumbs-up"></p>
					<%= post.favorites.count %>
				    <% end %>
				<% end %>
					<p class="glyphicon glyphicon-comment"></p>
	           	  <%= post.post_comments.count %>
			</div>
			</div>
            <% end %>
	    </div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="hensyu">
	<div class="fail">
<div class="container">
	<div class="row">
		<h4>新規投稿</h4>
		<%= form_for(@post) do |f| %>
		  <h5>画像</h5>
		  <%= f.attachment_field :image %>
		  <h5>レシピ</h5>
		  <%= f.text_field :recipe_name %>
		  <h5>内容</h5>
		  <%= f.text_area :caption, size: "50x5" %>

		  <%= f.submit "送信" %>
		<% end %>
	</div>
</div>
</div>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="row">
    <div class="wrap">
      <div class="recipesearch">
        <h1>レシピを検索</h1>
        <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
          <%= f.text_field :recipe_name %>
          <%= f.submit :search %>
        <% end %>
      </div>

      <% @posts.each do |post|%>
      <div class="searchimage">
       <%= link_to post_path(post) do %>
       <div class="recipesearchimage">
        <%= attachment_image_tag post, :image, format: 'jpeg', size: "600x400" %>
      </div>
       <% end %>
       <div class="searchname">
       <%= post.recipe_name %>
       </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="wrap">
			<div class="space"></div>
			<div class="sidespace">
			<div class="profile_gazou">
				<%= attachment_image_tag @post.user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img" %>
			</div>
			<div class="profile_name">
				<div class="name_space">
				 <%= @post.user.name %>
				</div>
				 <div class="recipe_title">
				  <p class="underline"><%= @post.recipe_name %></p>
			    </div>
			</div>
			<div class="content_gazou">
				<div class="gazou">
				<%= link_to post_path(@post) do %>
			  		<%= attachment_image_tag @post, :image, format: 'jpeg', size: "600x400" %>
				<% end %>
				</div>
			</div>
			<div class="content_comment">
			    <div class="recipe_caption">
				  <%= @post.caption %>
			    </div>
				<% if @post.favorited_by?(current_user) %>
					<%= link_to post_favorites_path(@post), method: :delete do %>
				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				    <p class="glyphicon glyphicon-thumbs-up"></p>
					<%= @post.favorites.count %>
				    <% end %>
				<% else %>
				    <%= link_to post_favorites_path(@post), method: :post do %>
					<i class="fa fa-heart-o" aria-hidden="true"></i>
					<p class="glyphicon glyphicon-thumbs-up"></p>
					<%= @post.favorites.count %>
				    <% end %>
				<% end %>
					<p class="glyphicon glyphicon-comment"></p>
	           	  <%= @post.post_comments.count %>
			</div>
			</div>
			<div class="comments-area">
			<%= form_for [@post, @post_comment] do |f| %>
	  			<%= f.text_area :comment, size: "80x2" %>
	  			<%= f.submit "コメント" %>
			<% end %>
			</div>
			<% @post.post_comments.each do |post| %>
			<div class="comments-line">
			<%= attachment_image_tag @post.user, :profile_image, format: 'jpeg', size: "50x50", class: "img-circle pull-left profile-img" %>
			<%= post.comment %>
			</div>
			<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<div class="hensyu">
	<div class="fail">
<h1>プロフィール編集</h1>
<br>
<%= form_for(@user) do |f| %>
	<p>画像</p>
	<%= f.attachment_field :profile_image %>
	<br>
	<p>名前</p>
	<%= f.text_field :name %>
	<br>
	<br>
	<p>自己紹介</p>
	<%= f.text_area :userinfo %>

	<%= f.submit "保存" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="wrap">
			<div class="userarea">
				<p><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img" %></p>
				<div class="myinfo">
				<p class="name"><%= @user.name %></p>
				<p class="info"><%= @user.userinfo %></p>

				<% if @user.id == current_user.id %>
				  <%= link_to "変更", edit_user_path, class: 'btn btn-default' %>
				<% end %>
				</div>
			</div>
			<% @posts.each do |post| %>
			<div class="space"></div>
			<div class="sidespace">
			<div class="profile_gazou">
				<%= attachment_image_tag post.user, :profile_image, format: 'jpeg', size: "100x100", class: "img-circle pull-left profile-img" %>
			</div>
			<div class="profile_name">
				<div class="name_space">
				<%= post.user.name %>
				<div class="right-display">
				<% if post.user == current_user %>
					<%= link_to "編集", edit_post_path(post), class: 'btn btn-default' %>
				<% end %>
				<% if post.user == current_user %>
					<%= link_to "削除", post_path(post), method: :delete, class: 'btn btn-default' %>
				<% end %>
				</div>
				</div>
				 <div class="recipe_title">
				  <p class="underline"><%= post.recipe_name %></p>
			    </div>
			</div>
			<div class="content_gazou">
				<div class="gazou">
				<%= link_to post_path(post) do %>
				 <%= attachment_image_tag post, :image, format: 'jpeg', size: "600x400" %>
				<% end %>
				</div>
			</div>
			<div class="content_comment">
			    <div class="recipe_caption">
				  <%= post.caption %>
			    </div>
				<% if post.favorited_by?(current_user) %>
					<%= link_to post_favorites_path(post), method: :delete do %>
				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				    <p class="glyphicon glyphicon-thumbs-up"></p>
					<%= post.favorites.count %>
				    <% end %>
				<% else %>
				    <%= link_to post_favorites_path(post), method: :post do %>
					<i class="fa fa-heart-o" aria-hidden="true"></i>
					<p class="glyphicon glyphicon-thumbs-up"></p>
					<%= post.favorites.count %>
				    <% end %>
				<% end %>
					<p class="glyphicon glyphicon-comment"></p>
	           	  <%= post.post_comments.count %>
			</div>
			</div>
            <% end %>
	</div>
   </div>
</div>

app/views/users/top.html.erb
<div class="toppage">
<div class="have"></div>
<h1>Recipe Diary</h1>
<br>
<%= link_to "ログイン", new_user_session_path, class: "btn btn-primary" %>
<%= link_to "アカウント作成", new_user_registration_path, class: "btn btn-primary" %>
<br>
<br>
アカウントを作られてない方は<%= link_to "こちら", new_user_registration_path %>

</div>